import {
  VideoGenerationReferenceType,
} from '@google/genai';
import { createGoogleGenAI } from '../../../shared/auth';
import type {
  Video,
  VideoGenerationReferenceImage,
} from '@google/genai';

export const GenerationMode = {
  TEXT_TO_VIDEO: 'TEXT_TO_VIDEO',
  FRAMES_TO_VIDEO: 'FRAMES_TO_VIDEO',
  REFERENCES_TO_VIDEO: 'REFERENCES_TO_VIDEO',
  EXTEND_VIDEO: 'EXTEND_VIDEO',
} as const;

export type GenerationMode = typeof GenerationMode[keyof typeof GenerationMode];

export interface GenerateVideoParams {
  prompt?: string;
  aspectRatio: '1:1' | '16:9' | '9:16';
  resolution: '720p' | '1080p';
  mode: GenerationMode;
  model?: string;
  startFrame?: { base64: string; type: string; name?: string };
  endFrame?: { base64: string; type: string; name?: string };
  isLooping?: boolean;
  referenceImages?: { base64: string; type: string; name?: string }[];
  styleImage?: { base64: string; type: string; name?: string };
  inputVideoObject?: any;
}

export interface GenerateImageParams {
  prompt: string;
  aspectRatio: '1:1' | '16:9' | '9:16';
  referenceImageBase64?: string;
  model?: string;
}

export const generateImage = async (
  params: GenerateImageParams,
  apiKey: string,
): Promise<{ objectUrl: string; blob: Blob; base64: string }> => {
  console.log('Starting image generation with params:', params);

  const ai = createGoogleGenAI(apiKey);
  const modelName = params.model || 'gemini-3.1-flash-image';
  const isGeminiImageModel = modelName.toLowerCase().includes('gemini') || modelName.toLowerCase().includes('banana');

  if (isGeminiImageModel) {
    console.log(`Using Gemini multimodal generateContent workflow for model: ${modelName}`);
    let ratioInstruction = '';
    if (params.aspectRatio === '16:9') {
      ratioInstruction = ' (Generate in landscape 16:9 aspect ratio)';
    } else if (params.aspectRatio === '9:16') {
      ratioInstruction = ' (Generate in portrait 9:16 aspect ratio)';
    } else {
      ratioInstruction = ' (Generate in square 1:1 aspect ratio)';
    }

    const response = await ai.models.generateContent({
      model: modelName,
      contents: `${params.prompt}${ratioInstruction}`,
      config: {
        responseModalities: ['IMAGE'],
      }
    });

    let base64Str = '';
    const candidate = response.candidates?.[0];
    if (candidate?.content?.parts) {
      for (const part of candidate.content.parts) {
        if (part.inlineData && part.inlineData.data) {
          base64Str = part.inlineData.data;
          break;
        }
      }
    }

    if (!base64Str) {
      throw new Error('API 回傳內容未包含有效的圖片資料。請確認您的 API 金鑰是否支援此模型。');
    }

    const mimeType = 'image/jpeg';
    const res = await fetch(`data:${mimeType};base64,${base64Str}`);
    const blob = await res.blob();
    const objectUrl = URL.createObjectURL(blob);

    return { objectUrl, blob, base64: base64Str };
  } else {
    const base64Data = params.referenceImageBase64 && params.referenceImageBase64.includes('base64,')
      ? params.referenceImageBase64.split('base64,')[1]
      : params.referenceImageBase64;

    const payload: any = {
      model: modelName,
      prompt: params.prompt,
      config: {
        numberOfImages: 1,
        aspectRatio: params.aspectRatio,
        outputMimeType: 'image/jpeg',
      },
    };

    if (base64Data) {
      payload.config.referenceImage = {
        imageBytes: base64Data,
      };
    }

    const response = await ai.models.generateImages(payload);
    const generatedImage = response.generatedImages?.[0];
    if (!generatedImage || !generatedImage.image?.imageBytes) {
      throw new Error('No image was generated by Imagen.');
    }

    const base64Str = generatedImage.image.imageBytes;
    const mimeType = 'image/jpeg';
    const res = await fetch(`data:${mimeType};base64,${base64Str}`);
    const blob = await res.blob();
    const objectUrl = URL.createObjectURL(blob);

    return { objectUrl, blob, base64: base64Str };
  }
};

export const generateVideo = async (
  params: GenerateVideoParams,
  apiKey: string,
): Promise<{ objectUrl: string; blob: Blob; uri: string; video: Video }> => {
  console.log('Starting video generation with params:', params);

  const ai = createGoogleGenAI(apiKey);

  const config: any = {
    numberOfVideos: 1,
    resolution: params.resolution,
  };

  if (params.mode !== GenerationMode.EXTEND_VIDEO) {
    config.aspectRatio = params.aspectRatio;
  }

  if (params.isLooping !== undefined) {
    config.loop = params.isLooping;
  }

  const generateVideoPayload: any = {
    model: params.model || 'veo-3.1-generate-preview',
    prompt: params.prompt,
    config,
  };

  if (params.mode === GenerationMode.FRAMES_TO_VIDEO) {
    if (params.startFrame) {
      generateVideoPayload.image = {
        imageBytes: params.startFrame.base64.includes('base64,')
          ? params.startFrame.base64.split('base64,')[1]
          : params.startFrame.base64,
        mimeType: params.startFrame.type,
      };
      console.log(`Generating with start frame: ${params.startFrame.name || 'uploaded_frame'}`);
    }

    const finalEndFrame = params.isLooping ? params.startFrame : params.endFrame;
    if (finalEndFrame) {
      generateVideoPayload.config.lastFrame = {
        imageBytes: finalEndFrame.base64.includes('base64,')
          ? finalEndFrame.base64.split('base64,')[1]
          : finalEndFrame.base64,
        mimeType: finalEndFrame.type,
      };
      if (params.isLooping) {
        console.log(`Generating a looping video using start frame as end frame`);
      } else {
        console.log(`Generating with end frame: ${finalEndFrame.name || 'uploaded_frame'}`);
      }
    }
  } else if (params.mode === GenerationMode.REFERENCES_TO_VIDEO) {
    const referenceImagesPayload: VideoGenerationReferenceImage[] = [];

    if (params.referenceImages) {
      for (const img of params.referenceImages) {
        console.log(`Adding reference image: ${img.name || 'reference_image'}`);
        referenceImagesPayload.push({
          image: {
            imageBytes: img.base64.includes('base64,')
              ? img.base64.split('base64,')[1]
              : img.base64,
            mimeType: img.type,
          },
          referenceType: VideoGenerationReferenceType.ASSET,
        });
      }
    }

    if (params.styleImage) {
      console.log(`Adding style image as a reference: ${params.styleImage.name || 'style_image'}`);
      referenceImagesPayload.push({
        image: {
          imageBytes: params.styleImage.base64.includes('base64,')
            ? params.styleImage.base64.split('base64,')[1]
            : params.styleImage.base64,
          mimeType: params.styleImage.type,
        },
        referenceType: VideoGenerationReferenceType.STYLE,
      });
    }

    if (referenceImagesPayload.length > 0) {
      generateVideoPayload.config.referenceImages = referenceImagesPayload;
    }
  } else if (params.mode === GenerationMode.EXTEND_VIDEO) {
    if (params.inputVideoObject) {
      generateVideoPayload.video = params.inputVideoObject;
      console.log(`Generating extension from input video object.`);
    } else {
      throw new Error('An input video object is required to extend a video.');
    }
  }

  console.log('Submitting video generation request...', generateVideoPayload);
  let operation = await ai.models.generateVideos(generateVideoPayload);
  console.log('Video generation operation started:', operation);

  while (!operation.done) {
    await new Promise((resolve) => setTimeout(resolve, 10000));
    console.log('...Generating...');
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  if (operation.error) {
    console.error('Operation failed with error:', operation.error);
    throw new Error(
      `Video generation failed: ${operation.error.message || 'Unknown error'}`,
    );
  }

  if (operation?.response) {
    const videos = operation.response.generatedVideos;

    if (!videos || videos.length === 0) {
      throw new Error('No videos were generated.');
    }

    const firstVideo = videos[0];
    if (!firstVideo?.video?.uri) {
      throw new Error('Generated video is missing a URI.');
    }
    const videoObject = firstVideo.video;

    const url = decodeURIComponent(videoObject.uri!);
    console.log('Fetching video from:', url);

    const res = await fetch(`${url}&key=${apiKey}`);

    if (!res.ok) {
      throw new Error(`Failed to fetch video: ${res.status} ${res.statusText}`);
    }

    const videoBlob = await res.blob();
    const objectUrl = URL.createObjectURL(videoBlob);

    return { objectUrl, blob: videoBlob, uri: url, video: videoObject };
  } else {
    console.error('Operation failed:', operation);
    throw new Error('No videos generated.');
  }
};
